
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import Bootstrap from "./component/Bootstrap";
import { Navbar } from "./component/Navbar";
import { Footer } from "./component/Footer";


export const metadata = {
  title: "TutorialWebsite | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
      </head>
      <body >
        
        {children}
        <Bootstrap/>
       
      </body>
    </html>
  );
}
